### PR TITLE
Optimized autoyapf.yml

### PR DESCRIPTION
**Pull request by prahasR**
Solves #21. 
## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
## Checklist:
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by ShivamSinghal1 — CHANGES_REQUESTED** [review]
This is not what we want. If we add a new app, we have to update this, also this is almost the same as of previous one. 

What do we expect? 
yapf will run only on the changes files. Say if we have just one file updated, then why check all the other files for formatting. 
You can get the details of changed files and file name by 
```
URL="https://api.github.com/repos/${{github.repository}}/pulls/${{ github.event.pull_request.number }}/files?per_page=100"
FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
echo $FILES
```

**Comment by prahasR** [comment]
@ShivamSinghal1 so the above code will give me list of all the files changed in the pull request?

**Comment by prahasR** [comment]
@ShivamSinghal1 I did the required changes, can you check now. If there is still some issue then please let me know.

**Comment by ShivamSinghal1** [comment]
Thats the main issue we are facing, we can't do it like that, if we pass non .py file name, yapf throws an error.

Thats why we have to filter .py files from the changes one.

**Comment by prahasR** [comment]
@ShivamSinghal1 modified it, please review it once.

**Review by ShivamSinghal1 — APPROVED** [review]

**Pull request merged**
